global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 5s

rule_files:
  # - "*.rule.yml"

scrape_configs:
  - job_name: prometheus

    honor_labels: true

    scheme: http
    metrics_path: /metrics

    static_configs:
      - targets: ["webapi:5000"]
        labels:
          service_name: AppMetricsWebApi